[build]
builder = "nixpacks"
buildCommand = "npm install && npm run build"

[deploy]
startCommand = "npm run start"
# Required variable on this service:
# API_URL=https://web-production-6447a.up.railway.app
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5
